apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-web-app
  template:
    metadata:
      labels:
        app: gitops-web-app
    spec:
      containers:
        - name: gitops-web-app
          image: wrohanar/gitops-web-app:latest
          ports:
            - containerPort: 3000
