name: Deploy to Kubernetes with ArgoCD and Flux

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        kubectl-version: 'latest'  # Optional: specify kubectl version

    - name: Create .kube directory
      run: mkdir -p ~/.kube

    - name: Set KUBECONFIG environment variable
      run: echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

    - name: Verify kubectl connection
      run: kubectl cluster-info

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/deployment.yaml --validate=false
        kubectl apply -f kubernetes/service.yaml --validate=false
