name: Deploy to Kubernetes with ArgoCD and Flux

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}  # Make sure this secret has the correct kubeconfig

    - name: Verify kubectl connection
      run: kubectl cluster-info

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/deployment.yaml --validate=false
        kubectl apply -f kubernetes/service.yaml --validate=false
